export default {
    DASHBOARD: "DashboardModule",
    CLIENTS: "ClientModule",
    CLIENTDETAILS: "ClientDetailsModule",
    INTENTS: "IntentModule",
    INTENTHANDLERS: "IntentHandlerModule",
    IntentHandlerDetails: "IntentHandlerDetailsModule",
    IntentHandlerAction: "IntentHandlerActionModule",
    IntentHandlerAdd: "IntentHandlerAddModule",
    SKILLS: "SkillModule",
    ENTITIES: "EntitiesModule",
    INTEGRATIONS: "IntegrationsModule",
    ALERTS: "AlertsModule",
    AlertsDetais: "AlertsDetailsModule",
    AlertsAction: "AlertsActionModule",
}